### ISSUE TITLE
Does `@overrideType` Still Apply?

### ISSUE THREAD

**Issue by shellscape** [graphile/small-examples#5]
### Summary

Hey @benjie I ran across this example: https://github.com/graphile/cookbook/blob/eff6c0d79d1c87b4e7f9c0a7130d008d65813274/examples/json_structure/db/init.sql#L12 and noticed the `@overrideType` smart tag. It's not documented anywhere and upon trying it locally doesn't appear to do anything or have any effect.

Is that still a valid smart tag?

**Comment by benjie** [comment]
It's defined by the plugin that example uses:

https://github.com/graphile/cookbook/blob/eff6c0d79d1c87b4e7f9c0a7130d008d65813274/examples/json_structure/JSONStructurePlugin.js#L46
